-- Categorías iniciales
INSERT INTO categorias (id, name, slug, description, icon, orden) VALUES
  ('plegadizas', 'Plegadizas', 'plegadizas', 'Cajas y empaques plegables para retail y consumo masivo.', '📦', 1),
  ('bolsas', 'Bolsas', 'bolsas', 'Bolsas impresas de papel y materiales especiales.', '🛍️', 2),
  ('exhibidores', 'Exhibidores', 'exhibidores', 'Displays y exhibidores para punto de venta.', '🏪', 3),
  ('bandejas', 'Bandejas', 'bandejas', 'Bandejas para alimentos y productos delicados.', '🍱', 4),
  ('vasos', 'Vasos', 'vasos', 'Vasos impresos para bebidas y promociones.', '🥤', 5),
  ('empaques-especiales', 'Empaques especiales', 'empaques-especiales', 'Soluciones personalizadas para necesidades únicas.', '🎁', 6),
  ('material-pop', 'Material POP', 'material-pop', 'Material publicitario en punto de venta.', '📢', 7),
  ('otros', 'Otros productos', 'otros', 'Folders, etiquetas, calendarios y más.', '📋', 8)
ON CONFLICT (id) DO NOTHING;

-- Productos iniciales (placeholders SVG)
INSERT INTO productos (id, name, slug, category_id, short_description, description, image, gallery, materials, finishes, applications) VALUES
  ('1', 'Caja plegadiza retail', 'caja-plegadiza-retail', 'plegadizas',
   'Caja plegadiza de cartulina para exhibición en góndola.',
   'Caja plegadiza diseñada para maximizar la visibilidad del producto en punto de venta.',
   'data:image/svg+xml,%3Csvg xmlns=''http://www.w3.org/2000/svg'' width=''600'' height=''400''%3E%3Crect fill=''%23E4007C'' width=''600'' height=''400''/%3E%3Ctext x=''50%25'' y=''50%25'' fill=''%23fff'' font-size=''24'' text-anchor=''middle''%3EPlegadiza%3C/text%3E%3C/svg%3E',
   '[]'::jsonb, '["Cartulina SBS 300g"]'::jsonb, '["Barniz UV spot"]'::jsonb, '["Retail"]'::jsonb),
  ('2', 'Bolsa kraft impresa', 'bolsa-kraft-impresa', 'bolsas',
   'Bolsa de papel kraft con impresión a todo color.',
   'Bolsa ecológica de papel kraft con asas reforzadas.',
   'data:image/svg+xml,%3Csvg xmlns=''http://www.w3.org/2000/svg'' width=''600'' height=''400''%3E%3Crect fill=''%2300AEEF'' width=''600'' height=''400''/%3E%3Ctext x=''50%25'' y=''50%25'' fill=''%23fff'' font-size=''24'' text-anchor=''middle''%3EBolsa%3C/text%3E%3C/svg%3E',
   '[]'::jsonb, '["Papel kraft 120g"]'::jsonb, '["Impresión flexo"]'::jsonb, '["Retail"]'::jsonb),
  ('3', 'Exhibidor de piso', 'exhibidor-de-piso', 'exhibidores',
   'Display de cartón corrugado para punto de venta.',
   'Exhibidor de piso de alta resistencia con diseño personalizado.',
   'data:image/svg+xml,%3Csvg xmlns=''http://www.w3.org/2000/svg'' width=''600'' height=''400''%3E%3Crect fill=''%23FFD600'' width=''600'' height=''400''/%3E%3Ctext x=''50%25'' y=''50%25'' fill=''%23fff'' font-size=''24'' text-anchor=''middle''%3EExhibidor%3C/text%3E%3C/svg%3E',
   '[]'::jsonb, '["Cartón corrugado"]'::jsonb, '["Impresión directa"]'::jsonb, '["Supermercados"]'::jsonb),
  ('4', 'Bandeja para alimentos', 'bandeja-alimentos', 'bandejas',
   'Bandeja termoformada con tapa impresa.',
   'Bandeja diseñada para alimentos listos para consumir.',
   'data:image/svg+xml,%3Csvg xmlns=''http://www.w3.org/2000/svg'' width=''600'' height=''400''%3E%3Crect fill=''%234CAF50'' width=''600'' height=''400''/%3E%3Ctext x=''50%25'' y=''50%25'' fill=''%23fff'' font-size=''24'' text-anchor=''middle''%3EBandeja%3C/text%3E%3C/svg%3E',
   '[]'::jsonb, '["PET reciclable"]'::jsonb, '["Termoformado"]'::jsonb, '["Alimentos"]'::jsonb),
  ('5', 'Vaso promocional', 'vaso-promocional', 'vasos',
   'Vaso impreso para campañas y eventos.',
   'Vaso de papel o plástico con impresión personalizada.',
   'data:image/svg+xml,%3Csvg xmlns=''http://www.w3.org/2000/svg'' width=''600'' height=''400''%3E%3Crect fill=''%239C27B0'' width=''600'' height=''400''/%3E%3Ctext x=''50%25'' y=''50%25'' fill=''%23fff'' font-size=''24'' text-anchor=''middle''%3EVaso%3C/text%3E%3C/svg%3E',
   '[]'::jsonb, '["Papel PE"]'::jsonb, '["Impresión offset"]'::jsonb, '["Eventos"]'::jsonb),
  ('6', 'Empaque premium', 'empaque-premium', 'empaques-especiales',
   'Empaque de lujo con acabados especiales.',
   'Solución de empaque premium con repujado, foil y barnices selectivos.',
   'data:image/svg+xml,%3Csvg xmlns=''http://www.w3.org/2000/svg'' width=''600'' height=''400''%3E%3Crect fill=''%231a1a1a'' width=''600'' height=''400''/%3E%3Ctext x=''50%25'' y=''50%25'' fill=''%23fff'' font-size=''24'' text-anchor=''middle''%3EPremium%3C/text%3E%3C/svg%3E',
   '[]'::jsonb, '["Cartulina premium"]'::jsonb, '["Foil stamping"]'::jsonb, '["Cosmética"]'::jsonb),
  ('7', 'Stopper de góndola', 'stopper-gondola', 'material-pop',
   'Material POP para destacar productos en anaquel.',
   'Stopper de cartulina con diseño llamativo.',
   'data:image/svg+xml,%3Csvg xmlns=''http://www.w3.org/2000/svg'' width=''600'' height=''400''%3E%3Crect fill=''%23FF5722'' width=''600'' height=''400''/%3E%3Ctext x=''50%25'' y=''50%25'' fill=''%23fff'' font-size=''24'' text-anchor=''middle''%3EPOP%3C/text%3E%3C/svg%3E',
   '[]'::jsonb, '["Cartulina 14pt"]'::jsonb, '["Barniz UV"]'::jsonb, '["Retail"]'::jsonb),
  ('8', 'Folder corporativo', 'folder-corporativo', 'otros',
   'Folder institucional con bolsillo interior.',
   'Folder corporativo con impresión a todo color.',
   'data:image/svg+xml,%3Csvg xmlns=''http://www.w3.org/2000/svg'' width=''600'' height=''400''%3E%3Crect fill=''%23607D8B'' width=''600'' height=''400''/%3E%3Ctext x=''50%25'' y=''50%25'' fill=''%23fff'' font-size=''24'' text-anchor=''middle''%3EFolder%3C/text%3E%3C/svg%3E',
   '[]'::jsonb, '["Cartulina couché 300g"]'::jsonb, '["Laminado mate"]'::jsonb, '["Corporativo"]'::jsonb)
ON CONFLICT (id) DO NOTHING;
